CREATE TABLE IF NOT EXISTS reports (
  request_id INT AUTO_INCREMENT PRIMARY KEY,
  filed_by VARCHAR(255) NOT NULL,
  concern VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(50) NOT NULL,
  current_approval_stage VARCHAR(50) NOT NULL,
  is_fully_approved BOOLEAN NOT NULL DEFAULT FALSE,
  date_reported DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_updated DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);